"""Agent Lab — Export generators for standalone agent code."""

from app.models import Agent


# ── Provider base URL mapping ─────────────────────────────────────────────────

_PROVIDER_BASE_URLS: dict[str, str | None] = {
    "openai": None,          # uses default
    "anthropic": None,       # uses default
    "openrouter": "https://openrouter.ai/api/v1",
}

_PROVIDER_ENV_VARS: dict[str, str] = {
    "openai": "OPENAI_API_KEY",
    "anthropic": "ANTHROPIC_API_KEY",
    "openrouter": "OPENROUTER_API_KEY",
}


# ── Python Script ─────────────────────────────────────────────────────────────

def generate_python_script(agent: Agent) -> str:
    """Generate a standalone Python CLI script for the agent."""
    env_var = _PROVIDER_ENV_VARS.get(agent.provider, "API_KEY")
    base_url_line = ""
    if _PROVIDER_BASE_URLS.get(agent.provider):
        base_url_line = f'base_url="{_PROVIDER_BASE_URLS[agent.provider]}",'

    return f'''\
#!/usr/bin/env python3
"""
Agent: {agent.name}
{agent.description or ""}

Generated by Agent Lab.
Usage: python agent.py "your task here"

Requirements:
    pip install openai
"""

import os
import sys
from openai import OpenAI

# --- Configuration ---
API_KEY = os.environ.get("{env_var}")
if not API_KEY:
    print("[error] {env_var} environment variable not set")
    sys.exit(1)

SYSTEM_PROMPT = """{agent.system_prompt}"""

MODEL = "{agent.model}"

# --- Client ---
client = OpenAI(
    api_key=API_KEY,
    {base_url_line}
)


def run(task: str) -> str:
    """Run the agent with the given task."""
    print(f"[agent] Running: {{task}}")
    response = client.chat.completions.create(
        model=MODEL,
        messages=[
            {{"role": "system", "content": SYSTEM_PROMPT}},
            {{"role": "user", "content": task}},
        ],
    )
    result = response.choices[0].message.content or ""
    print("[agent] Done.")
    return result


if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage: python agent.py \\"your task here\\"")
        sys.exit(1)

    task = " ".join(sys.argv[1:])
    output = run(task)
    print("\\n--- Result ---")
    print(output)
'''


# ── FastAPI App ───────────────────────────────────────────────────────────────

def generate_fastapi_app(agent: Agent) -> str:
    """Generate a deployable FastAPI app for the agent."""
    env_var = _PROVIDER_ENV_VARS.get(agent.provider, "API_KEY")
    base_url_line = ""
    if _PROVIDER_BASE_URLS.get(agent.provider):
        base_url_line = f'    base_url="{_PROVIDER_BASE_URLS[agent.provider]}",'

    return f'''\
#!/usr/bin/env python3
"""
Agent: {agent.name}
{agent.description or ""}

Generated by Agent Lab.

Requirements (requirements.txt):
    fastapi>=0.111
    uvicorn[standard]>=0.29
    openai>=1.30
    pydantic>=2.0

Run:
    {env_var}=your_key uvicorn agent_app:app --host 0.0.0.0 --port 8000
"""

import os
from fastapi import FastAPI, HTTPException
from pydantic import BaseModel
from openai import OpenAI

# --- Configuration ---
API_KEY = os.environ.get("{env_var}")
if not API_KEY:
    raise RuntimeError("{env_var} environment variable is required")

SYSTEM_PROMPT = """{agent.system_prompt}"""
MODEL = "{agent.model}"

# --- FastAPI app ---
app = FastAPI(
    title="{agent.name}",
    description="{agent.description or 'Generated by Agent Lab'}",
    version="1.0.0",
)

client = OpenAI(
    api_key=API_KEY,
{base_url_line}
)


class ChatRequest(BaseModel):
    message: str


class ChatResponse(BaseModel):
    reply: str
    model: str


@app.get("/health")
def health():
    """Health check endpoint."""
    return {{"status": "ok", "agent": "{agent.name}"}}


@app.post("/chat", response_model=ChatResponse)
def chat(request: ChatRequest):
    """Send a message to the agent and get a response."""
    try:
        response = client.chat.completions.create(
            model=MODEL,
            messages=[
                {{"role": "system", "content": SYSTEM_PROMPT}},
                {{"role": "user", "content": request.message}},
            ],
        )
        reply = response.choices[0].message.content or ""
        return ChatResponse(reply=reply, model=MODEL)
    except Exception as exc:
        raise HTTPException(status_code=500, detail=str(exc)) from exc
'''


# ── Dockerfile ────────────────────────────────────────────────────────────────

def generate_dockerfile(agent: Agent) -> str:
    """Generate a Dockerfile that packages the FastAPI agent app."""
    env_var = _PROVIDER_ENV_VARS.get(agent.provider, "API_KEY")

    return f'''\
# Generated by Agent Lab — {agent.name}
# Build:  docker build -t agent-{agent.name.lower().replace(" ", "-")} .
# Run:    docker run -e {env_var}=your_key -p 8000:8000 agent-{agent.name.lower().replace(" ", "-")}

FROM python:3.11-slim

LABEL maintainer="Agent Lab"
LABEL description="{agent.description or agent.name}"

WORKDIR /app

# Install dependencies first (better layer caching)
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy agent source
COPY agent_app.py .

# Expose port
EXPOSE 8000

# Health check
HEALTHCHECK --interval=30s --timeout=5s --start-period=10s \\
    CMD python -c "import urllib.request; urllib.request.urlopen(\'http://localhost:8000/health\')"

# Run
CMD ["uvicorn", "agent_app:app", "--host", "0.0.0.0", "--port", "8000"]

# ---
# requirements.txt content:
# fastapi>=0.111
# uvicorn[standard]>=0.29
# openai>=1.30
# pydantic>=2.0
'''
